### ISSUE TITLE
Support for named modules

### ISSUE THREAD

**Issue by bzbetty** [prantlf/requirejs-esm-converter#1]
Define can have 3 arguments
example:

```define('api', ['jquery', 'debug'], function ($, debug) {```

https://requirejs.org/docs/api.html#modulename

however currently this errors with "too many arguments"

**Comment by prantlf** [comment]
An interesting request. Sources usually consist of unnamed modules, because module names are necessary first when multiple modules are built into a module bundle. But I admit that it's possible to name the source modules already, if it has some benefit.

When named modules get converted to ESM, importing them by the abstract names should continue working. Support for module naming may differ among module bundlers, but as soon as [import maps](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap) have been introduced for ESM, they should be supported as a standard.

Let me fix this and produce an import map with the explicitly named modules.

**Comment by prantlf** [comment]
Released in [1.2.0](https://github.com/prantlf/requirejs-esm-converter/releases/tag/v1.2.0).

If named modules are detected, the import map will be printed on the console or to a specified file. File paths will be as specified on the command line, usually relatively to the project root. They may need to be adjusted according to the project deployment.

The API for the module conversion - the `convert` function - returns the module name as an optional `name` property.

Thank you for reporting this!
